#!/bin/bash

# Apply spectrum background subtraction for XSPEC fitting
# 1. create QPB subtracted src and bkg spectra, suffixed "_sqpb.pi"
# 2. directly subtract backgrounds from src spectra

OBSIDS="0087940201 0551000201"

for obsid in $OBSIDS;
do

  cd "${XMM_PATH}/${obsid}/odf/repro"

  # Create temporary files; mathpha disallows dashes in filenames
  fstems="mos1S001_src mos2S002_src mos1S001_bkg mos2S002_bkg"
  cp mos1S001-src.pi     mos1S001_src.pi
  cp mos1S001-src-qpb.pi mos1S001_src_qpb.pi
  cp mos1S001-bkg.pi     mos1S001_bkg.pi
  cp mos1S001-bkg-qpb.pi mos1S001_bkg_qpb.pi
  cp mos2S002-src.pi     mos2S002_src.pi
  cp mos2S002-src-qpb.pi mos2S002_src_qpb.pi
  cp mos2S002-bkg.pi     mos2S002_bkg.pi
  cp mos2S002-bkg-qpb.pi mos2S002_bkg_qpb.pi
  if [[ $obsid = "0087940201" ]]; then
    fstems="${fstems} pnS003_src_os pnS003_bkg_os"
    cp pnS003-src-os.pi  pnS003_src_os.pi
    cp pnS003-src-qpb.pi pnS003_src_os_qpb.pi
    cp pnS003-bkg-os.pi  pnS003_bkg_os.pi
    cp pnS003-bkg-qpb.pi pnS003_bkg_os_qpb.pi
  fi

  # Subtract QPB spectra
  for fstem in $fstems;
  do
    # Spectrum units: (c)ounts, (r)ate
    uflag='C'
    if [[ $fstem =~ "pn" ]]; then
      uflag='R'
    fi
    mathpha expr="${fstem}.pi - ${fstem}_qpb.pi" outfil="!${fstem}_sqpb.pi" \
        units="${uflag}" properr='yes' \
        exposure="${fstem}.pi" backscal='%' areascal='%' \
        ncomments=0
    # areascal=1; backscal is same for QPB and observation spectra
    # (but different for src and bkg, so must store correct BACKSCAL value)
    # Exposure set by src/bkg spectrum; exp time not changed by QPB subtraction

    # raw spectrum has cts w/ Poisson error (keyword POISSERR='T')
    # QPB has cts and statistical error, much smaller than Poisson error
    # subtracting spectra -> Gaussian errors > POISS-0 errors
    # and anyways, any of POISS-0,1,2,3 will fail on channels with negative
    # counts (which does occur)
  done

  # Apply ARF ratio correction (eyeballed) for bkg spectra
  # Please note ratios are HARDCODED in mathpha calls
  if [[ $obsid = "0087940201" ]]; then
    mathpha expr="1.25 * mos1S001_bkg_sqpb.pi" outfil="!mos1S001_bkg_sqpb_arfcorr.pi" \
      units='C' exposure="mos1S001_bkg_sqpb.pi" backscal='%' areascal='%' \
      properr='yes' ncomments=0
    mathpha expr="1.32 * mos2S002_bkg_sqpb.pi" outfil="!mos2S002_bkg_sqpb_arfcorr.pi" \
      units='C' exposure="mos2S002_bkg_sqpb.pi" backscal='%' areascal='%' \
      properr='yes' ncomments=0
    mathpha expr="1.27 * pnS003_bkg_os_sqpb.pi" outfil="!pnS003_bkg_os_sqpb_arfcorr.pi" \
      units='R' exposure="pnS003_bkg_os_sqpb.pi" backscal='%' areascal='%' \
      properr='yes' ncomments=0
  fi
  if [[ $obsid = "0551000201" ]]; then
    mathpha expr=" 1.66 * mos1S001_bkg_sqpb.pi" outfil="!mos1S001_bkg_sqpb_arfcorr.pi" \
      units='C' exposure="mos1S001_bkg_sqpb.pi" backscal='%' areascal='%' \
      properr='yes' ncomments=0
    mathpha expr=" 1.67 * mos2S002_bkg_sqpb.pi" outfil="!mos2S002_bkg_sqpb_arfcorr.pi" \
      units='C' exposure="mos2S002_bkg_sqpb.pi" backscal='%' areascal='%' \
      properr='yes' ncomments=0
  fi

  # Subtract ARF-adjusted backgrounds
  mathpha expr="mos1S001_src_sqpb.pi - mos1S001_bkg_sqpb_arfcorr.pi" \
      outfil="!mos1S001_src_sqpb_sbkg.pi" \
      units='C' properr='yes' \
      exposure="mos1S001_src_sqpb.pi" \
      backscal="mos1S001_src_sqpb.pi" \
      areascal="mos1S001_src_sqpb.pi" \
      ncomments=0
  mathpha expr="mos2S002_src_sqpb.pi - mos2S002_bkg_sqpb_arfcorr.pi" \
      outfil="!mos2S002_src_sqpb_sbkg.pi" \
      units='C' properr='yes' \
      exposure="mos2S002_src_sqpb.pi" \
      backscal="mos2S002_src_sqpb.pi" \
      areascal="mos2S002_src_sqpb.pi" \
      ncomments=0
  if [[ $obsid = "0087940201" ]]; then
    mathpha expr="pnS003_src_os_sqpb.pi - pnS003_bkg_os_sqpb_arfcorr.pi" \
        outfil="!pnS003_src_os_sqpb_sbkg.pi" \
        units='R' properr='yes' \
        exposure="pnS003_src_os_sqpb.pi" \
        backscal="pnS003_src_os_sqpb.pi" \
        areascal="pnS003_src_os_sqpb.pi" \
        ncomments=0
  fi

  # Finally, set keywords and group
  # grppha sets group column in spectrum; no information is lost. Extra counts
  # (< min bin size) at highest channels are flagged BAD and skipped by XSPEC.
  grppha infile="mos1S001_src_sqpb_sbkg.pi" outfile="!mos1S001_src_sqpb_sbkg_grp50.pi" \
    comm="chkey BACKFILE NONE & \
          chkey RESPFILE mos1S001-src.rmf & \
          chkey ANCRFILE mos1S001-src.arf & \
          group min 50 & exit" \
    chatter=10
  grppha infile="mos2S002_src_sqpb_sbkg.pi" outfile="!mos2S002_src_sqpb_sbkg_grp50.pi" \
    comm="chkey BACKFILE NONE & \
          chkey RESPFILE mos2S002-src.rmf & \
          chkey ANCRFILE mos2S002-src.arf & \
          group min 50 & exit" \
    chatter=10
  if [[ $obsid = "0087940201" ]]; then
    grppha infile="pnS003_src_os_sqpb_sbkg.pi" outfile="!pnS003_src_os_sqpb_sbkg_grp50.pi" \
      comm="chkey BACKFILE NONE & \
            chkey RESPFILE pnS003-src.rmf & \
            chkey ANCRFILE pnS003-src.arf & \
            group min 50 & exit" \
      chatter=10
  fi

  # Experimental variant
  grppha infile="mos1S001_src_sqpb_sbkg.pi" outfile="!mos1S001_src_sqpb_sbkg_grp25.pi" \
    comm="chkey BACKFILE NONE & \
          chkey RESPFILE mos1S001-src.rmf & \
          chkey ANCRFILE mos1S001-src.arf & \
          group min 25 & exit" \
    chatter=10
  grppha infile="mos2S002_src_sqpb_sbkg.pi" outfile="!mos2S002_src_sqpb_sbkg_grp25.pi" \
    comm="chkey BACKFILE NONE & \
          chkey RESPFILE mos2S002-src.rmf & \
          chkey ANCRFILE mos2S002-src.arf & \
          group min 25 & exit" \
    chatter=10
  if [[ $obsid = "0087940201" ]]; then
    grppha infile="pnS003_src_os_sqpb_sbkg.pi" outfile="!pnS003_src_os_sqpb_sbkg_grp25.pi" \
      comm="chkey BACKFILE NONE & \
            chkey RESPFILE pnS003-src.rmf & \
            chkey ANCRFILE pnS003-src.arf & \
            group min 25 & exit" \
      chatter=10
  fi

  # ========== VARIANT, subtract background without QPB subtraction ==========

  # Apply ARF correction
  if [[ $obsid = "0087940201" ]]; then
    mathpha expr="1.25 * mos1S001_bkg.pi" outfil="!mos1S001_bkg_arfcorr.pi" \
      units='C' exposure="mos1S001_bkg.pi" backscal='%' areascal='%' \
      properr='yes' ncomments=0
    mathpha expr="1.32 * mos2S002_bkg.pi" outfil="!mos2S002_bkg_arfcorr.pi" \
      units='C' exposure="mos2S002_bkg.pi" backscal='%' areascal='%' \
      properr='yes' ncomments=0
    mathpha expr="1.27 * pnS003_bkg_os.pi" outfil="!pnS003_bkg_os_arfcorr.pi" \
      units='R' exposure="pnS003_bkg_os.pi" backscal='%' areascal='%' \
      properr='yes' ncomments=0
  fi
  if [[ $obsid = "0551000201" ]]; then
    mathpha expr=" 1.66 * mos1S001_bkg.pi" outfil="!mos1S001_bkg_arfcorr.pi" \
      units='C' exposure="mos1S001_bkg.pi" backscal='%' areascal='%' \
      properr='yes' ncomments=0
    mathpha expr=" 1.67 * mos2S002_bkg.pi" outfil="!mos2S002_bkg_arfcorr.pi" \
      units='C' exposure="mos2S002_bkg.pi" backscal='%' areascal='%' \
      properr='yes' ncomments=0
  fi

  # Subtract ARF-adjusted backgrounds
  mathpha expr="mos1S001_src.pi - mos1S001_bkg_arfcorr.pi" \
      outfil="!mos1S001_src_sbkg.pi" \
      units='C' properr='yes' \
      exposure="mos1S001_src.pi" \
      backscal="mos1S001_src.pi" \
      areascal="mos1S001_src.pi" \
      ncomments=0
  mathpha expr="mos2S002_src.pi - mos2S002_bkg_arfcorr.pi" \
      outfil="!mos2S002_src_sbkg.pi" \
      units='C' properr='yes' \
      exposure="mos2S002_src.pi" \
      backscal="mos2S002_src.pi" \
      areascal="mos2S002_src.pi" \
      ncomments=0
  if [[ $obsid = "0087940201" ]]; then
    mathpha expr="pnS003_src_os.pi - pnS003_bkg_os_arfcorr.pi" \
        outfil="!pnS003_src_os_sbkg.pi" \
        units='R' properr='yes' \
        exposure="pnS003_src_os.pi" \
        backscal="pnS003_src_os.pi" \
        areascal="pnS003_src_os.pi" \
        ncomments=0
  fi

  # Finally, set keywords and group
  # grppha sets group column in spectrum; no information is lost. Extra counts
  # (< min bin size) at highest channels are flagged BAD and skipped by XSPEC.
  grppha infile="mos1S001_src_sbkg.pi" outfile="!mos1S001_src_sbkg_grp50.pi" \
    comm="chkey BACKFILE NONE & \
          chkey RESPFILE mos1S001-src.rmf & \
          chkey ANCRFILE mos1S001-src.arf & \
          group min 50 & exit" \
    chatter=10
  grppha infile="mos2S002_src_sbkg.pi" outfile="!mos2S002_src_sbkg_grp50.pi" \
    comm="chkey BACKFILE NONE & \
          chkey RESPFILE mos2S002-src.rmf & \
          chkey ANCRFILE mos2S002-src.arf & \
          group min 50 & exit" \
    chatter=10
  if [[ $obsid = "0087940201" ]]; then
    grppha infile="pnS003_src_os_sbkg.pi" outfile="!pnS003_src_os_sbkg_grp50.pi" \
      comm="chkey BACKFILE NONE & \
            chkey RESPFILE pnS003-src.rmf & \
            chkey ANCRFILE pnS003-src.arf & \
            group min 50 & exit" \
      chatter=10
  fi
  # ========== END VARIANT, subtract background w/o QPB subtraction ==========

  # Remove temporary files
  rm mos1S001_src.pi
  rm mos1S001_src_qpb.pi
  rm mos1S001_bkg.pi
  rm mos1S001_bkg_qpb.pi
  rm mos2S002_src.pi
  rm mos2S002_src_qpb.pi
  rm mos2S002_bkg.pi
  rm mos2S002_bkg_qpb.pi
  if [[ $obsid = "0087940201" ]]; then
    rm pnS003_src_os.pi
    rm pnS003_src_os_qpb.pi
    rm pnS003_bkg_os.pi
    rm pnS003_bkg_os_qpb.pi
  fi

done
