#!/bin/bash

# Must run after sourcing sasinit (just to get ftools)

#if [ "$#" -ne 1 ]
#then
#    echo "Error: one argument (obsid) required, exiting"
#    exit 1
#fi

obsids="0087940201 0551000201"
exps="mos1S001 mos2S002 pnS003"
# NOTE: 0087940201 mos1S001 must be the first value

# TODO -- maybe take this as a command-line argument...
region_files=$(ls -1 ${XMM_PATH}/regs/*.reg) # Stolen from make_xmmregions

# Set a fiducial backscal value
# (obviously breaks if obsids or region naming changes)
fkeypar "0087940201/odf/repro/mos1S001-src-grp50.pi" BACKSCAL
FIDUCIAL_BACKSCAL="$(pget fkeypar value)"
FID_LABEL="0087940201 mos1S001 src"

for region_file in $region_files; do

  # Parse out region (obj) name (stolen from make_xmmregions)
  reg="$(basename $region_file | cut -d "." -f 1)"

  echo "${reg} backscal values:"

  for obsid in $obsids; do
    for exp in $exps; do

      if [[ "$obsid" == "0551000201" && "$exp" =~ "pn" ]]; then
        echo "  ${obsid} ${exp} skipped"
        continue
      fi

      fkeypar "${obsid}/odf/repro/${exp}-${reg}-grp50.pi" BACKSCAL
      backscal="$(pget fkeypar value)"

      backscal_ratio=$(perl -e "print ${backscal} / ${FIDUCIAL_BACKSCAL};")

      echo "  ${obsid} ${exp} BACKSCAL = $backscal (${reg}/(${FID_LABEL}) = $backscal_ratio)"

      # Lines below used to comprae src/background geometric (sky) areas
      # should generalize this to compare sub-regions.  But, not directly
      # useful currently.  TO do this:
      # 1. compute src region backscal first, and store in array
      # 2. for all regions other than src, compute ratio and compare to src
      #norm=$(perl -e "print( ($src_backscal) / ($bkg_backscal) );")
      #echo "src/bkg = $norm"
      #echo ""


    done
  done

  echo ""
done
