#!/bin/tcsh -f

# Standard event list pipeline for 0551000201 PN exposure only, without
# epreject correction.  For demonstration / comparison purposes.
# Must run on computer w/ >8 GB RAM, else pn-filter (espfilt) will fail.
# Aaron Tran
# Dec. 8 2015

# ------------------------
# Configuration parameters
# ------------------------

set OBSID = "0551000201"
set PNEXP = "S003"

# ------------------------
# Start of script commands
# ------------------------

mkdir -p "${XMM_PATH}/${OBSID}/odf/repro_no-epreject"
cd "${XMM_PATH}/${OBSID}/odf/repro_no-epreject"

# Generate event lists
epchain withoutoftime=true runepreject=N >& epchain_oot.log
epchain runepreject=N >& epchain.log

# Good time filtering (remove flares)
pn-filter >& pn-filter.log

foreach exp ($PNEXP)
    # Generate soft X-ray list/image to compare against run WITH epreject
    evselect table="pn${exp}-ori.fits" filteredset="pn${exp}-ori_vsoft.fits" \
        expression='(PHA>=20)&&(PI>=120)&&(PI<200)'
    evselect table="pn${exp}-oot.fits" filteredset="pn${exp}-oot_vsoft.fits" \
        expression='(PHA>=20)&&(PI>=120)&&(PI<200)'
    evselect table="pn${exp}-ori_vsoft.fits" withimageset=true \
    	imageset="pn${exp}-ori_vsoft-img.fits" xcolumn=DETX ycolumn=DETY \
	imagebinning=binSize ximagebinsize=100 yimagebinsize=100
    evselect table="pn${exp}-oot_vsoft.fits" withimageset=true \
    	imageset="pn${exp}-oot_vsoft-img.fits" xcolumn=DETX ycolumn=DETY \
	imagebinning=binSize ximagebinsize=100 yimagebinsize=100
end
