#!/bin/tcsh -f

# Standard event list pipeline for 0551000201 PN exposure only, without
# epreject correction.  For demonstration / comparison purposes.
# Must run on computer w/ >8 GB RAM, else pn-filter (espfilt) will fail.
# Aaron Tran
# Dec. 8 2015

# ------------------------
# Configuration parameters
# ------------------------

set OBSID = "0551000201"
set PNEXP = "S003"

# ------------------------
# Start of script commands
# ------------------------

mkdir -p "${XMM_PATH}/${OBSID}/odf/repro_no-epreject"
cd "${XMM_PATH}/${OBSID}/odf/repro_no-epreject"

# Generate event lists
epchain withoutoftime=true runepreject=N >& epchain_oot.log
epchain runepreject=N >& epchain.log

# Good time filtering (remove flares)
# Make symlinks to work around {mos,pn}-filter file renaming
pn-filter >& pn-filter.log
foreach exp ($PNEXP)
    ln -s pn${exp}-oot.fits P${OBSID}PN${exp}OOEVLI0000.FIT
    ln -s pn${exp}-ori.fits P${OBSID}PN${exp}PIEVLI0000.FIT

    # Generate soft X-ray list/image to compare against run WITH epreject
    evselect table="pn${exp}-ori.fits" filteredset="pn${exp}-ori_vsoft.fits" \
        expression='(PHA>=20)&&(PI>=120)&&(PI<200)'
    evselect table="pn${exp}-oot.fits" filteredset="pn${exp}-oot_vsoft.fits" \
        expression='(PHA>=20)&&(PI>=120)&&(PI<200)'

    evselect table="pn${exp}-ori_vsoft.fits" withimageset=true \
    	imageset="pn${exp}-ori_vsoft-img.fits" xcolumn=DETX ycolumn=DETY \
	imagebinning=binSize ximagebinsize=100 yimagebinsize=100 \
        expression='(PHA>=20)&&(PI>=120)&&(PI<200)'
    evselect table="pn${exp}-oot_vsoft.fits" withimageset=true \
    	imageset="pn${exp}-oot_vsoft-img.fits" xcolumn=DETX ycolumn=DETY \
	imagebinning=binSize ximagebinsize=100 yimagebinsize=100 \
        expression='(PHA>=20)&&(PI>=120)&&(PI<200)'
end


# Pat asks: is it necessary to run filtering 2x?  You should try this, maybe
# for 0551000201 at least.
# espfilt eventset=mos1-evt1.fits method=histogram clobber=no -V 6
# espfilt eventset=mos2-evt1.fits method=histogram clobber=no -V 6
# espfilt eventset=pn-evt1.fits method=histogram clobber=no -V 6

### Additional filtering steps if needed.
# Point source removal, special treatment for PN readout streaks
# any additional PATTERN / FLAG filtering (on top of what's already done in
# mos-filter and pn-filter) goes here.


