#!/bin/tcsh

# Wrapper script for a ton of XMM ESAS commands
# Must run on statler, espfilt (mos-filter, pn-filter) will fail on treble due
# to insufficient RAM.  (I think mos/pn-spectra are subject to this problem
# too, can't remember)
# Presupposes correct file prefixes for obsids 0087940201 and 0551000201
# Aaron Tran
# Oct. 5 2015, modified Oct. 25 2015

# CHANGE OF PLANS (Oct. 19 2015)
# RUN FROM DIRECTORY research/xmm/
source sasinit

cd /data/mpofls/atran/research/xmm/0087940201_redl/odf/
setenv SAS_ODF /data/mpofls/atran/research/xmm/0087940201_redl/odf/
cd repro
cifbuild
setenv SAS_CCF /data/mpofls/atran/research/xmm/0087940201_redl/odf/repro/ccf.cif
odfingest
setenv SAS_ODF `pwd`/`ls -1 *SUM.SAS`

# sas_setpaths 0087940201_redl

epchain withoutoftime=true >& epchain_oot.log
epchain >& epchain.log
emchain >& emchain.log
ls -lathr > lsl_chains.log

### Good time filtering (remove flares)
##mos-filter >& mos-filter.log
##mv command.csh mos_filter_cmd.csh
##pn-filter >& pn-filter.log
##ls -lathr > lsl_filters.log

### Spectrum extraction, source region
##mos-spectra prefix=1S001 caldb=/data/mpofls/atran/research/xmm/caldb region=regm1src.txt mask=0 elow=0 ehigh=0 ccd1=1 ccd2=1 ccd3=1 ccd4=1 ccd5=1 ccd6=1 ccd7=1 >& mos-spectra_1S001_src.log
##mv command.csh mos_spectra_regm1src_cmd.csh
##mos-spectra prefix=2S002 caldb=/data/mpofls/atran/research/xmm/caldb region=regm2src.txt mask=0 elow=0 ehigh=0 ccd1=1 ccd2=1 ccd3=1 ccd4=1 ccd5=1 ccd6=1 ccd7=1 >& mos-spectra_2S002_src.log
##mv command.csh mos_spectra_regm2src_cmd.csh
##pn-spectra prefix=S003 caldb=/data/mpofls/atran/research/xmm/caldb region=regpnsrc.txt mask=0 elow=0 ehigh=0 quad1=1 quad2=1 quad3=1 quad4=1 >& pn-spectra_S003_src.log
##mv command.csh mos_spectra_regpnsrc_cmd.csh
##ls -lathr > lsl_spectra_src.log
##
### Compute QPB for source region
##mos_back prefix=1S001 caldb=/data/mpofls/atran/research/xmm/caldb diag=2 elow=0 ehigh=0 ccd1=1 ccd2=1 ccd3=1 ccd4=1 ccd5=1 ccd6=1 ccd7=1 >& mos_back_1S001_src.log
##mos_back prefix=2S002 caldb=/data/mpofls/atran/research/xmm/caldb diag=2 elow=0 ehigh=0 ccd1=1 ccd2=1 ccd3=1 ccd4=1 ccd5=1 ccd6=1 ccd7=1 >& mos_back_2S002_src.log
##pn_back prefix=S003 caldb=/data/mpofls/atran/research/xmm/caldb diag=2 elow=0 ehigh=0 quad1=1 quad2=1 quad3=1 quad4=1 >& pn_back_S003_src.log
##ls -lathr > lsl_backspec_src.log
##
### Move files to avoid clobbering.  Currently, just the spectra + soft proton image for proton-scale
##mv mos1S001-obj.pi mos1S001-obj-src.pi 
##mv mos1S001-back.pi mos1S001-back-src.pi 
##mv mos1S001.rmf mos1S001-src.rmf 
##mv mos1S001.arf mos1S001-src.arf 
##mv mos1S001-obj-im-sp-det.fits mos2S002-im-sp-det-src.fits 
### MOS2
##mv mos2S002-obj.pi  mos2S002-obj-src.pi 
##mv mos2S002-back.pi mos2S002-back-src.pi 
##mv mos2S002.rmf     mos2S002-src.rmf 
##mv mos2S002.arf     mos2S002-src.arf 
##mv mos2S002-obj-im-sp-det.fits mos2S002-im-sp-det-src.fits 
### PN
##mv pnS003-obj.pi  pnS003-obj-src.pi 
##mv pnS003-back.pi pnS003-back-src.pi 
##mv pnS003.rmf     pnS003-src.rmf 
##mv pnS003.arf     pnS003-src.arf 
##mv pnS003-obj-im-sp-det.fits pnS003-sp-src.fits 
##mv pnS003-obj-os.pi          pnS003-obj-os-src.pi
##
### Spectrum extraction, background region
##mos-spectra prefix=1S001 caldb=/data/mpofls/atran/research/xmm/caldb region=regm1bkg.txt mask=0 elow=0 ehigh=0 ccd1=1 ccd2=1 ccd3=1 ccd4=1 ccd5=1 ccd6=1 ccd7=1 >& mos-spectra_1S001_bkg.log
##mv command.csh mos_spectra_regm1bkg_cmd.csh
##mos-spectra prefix=2S002 caldb=/data/mpofls/atran/research/xmm/caldb region=regm2bkg.txt mask=0 elow=0 ehigh=0 ccd1=1 ccd2=1 ccd3=1 ccd4=1 ccd5=1 ccd6=1 ccd7=1 >& mos-spectra_2S002_bkg.log
##mv command.csh mos_spectra_regm2bkg_cmd.csh
##pn-spectra prefix=S003 caldb=/data/mpofls/atran/research/xmm/caldb region=regpnbkg.txt mask=0 elow=0 ehigh=0 quad1=1 quad2=1 quad3=1 quad4=1 >& pn-spectra_S003_bkg.log
##mv command.csh mos_spectra_regpnbkg_cmd.csh
##ls -lathr > lsl_spectra_bkg.log
##
### Compute QPB for background region
##mos_back prefix=1S001 caldb=/data/mpofls/atran/research/xmm/caldb diag=2 elow=0 ehigh=0 ccd1=1 ccd2=1 ccd3=1 ccd4=1 ccd5=1 ccd6=1 ccd7=1 >& mos_back_1S001_bkg.log
##mos_back prefix=2S002 caldb=/data/mpofls/atran/research/xmm/caldb diag=2 elow=0 ehigh=0 ccd1=1 ccd2=1 ccd3=1 ccd4=1 ccd5=1 ccd6=1 ccd7=1 >& mos_back_2S002_bkg.log
##pn_back prefix=S003 caldb=/data/mpofls/atran/research/xmm/caldb diag=2 elow=0 ehigh=0 quad1=1 quad2=1 quad3=1 quad4=1 >& pn_back_S003_bkg.log
##ls -lathr > lsl_backspec_bkg.log
##
### Move files just so naming is consistent
##mv mos1S001-obj.pi mos1S001-obj-bkg.pi 
##mv mos1S001-back.pi mos1S001-back-bkg.pi 
##mv mos1S001.rmf mos1S001-bkg.rmf 
##mv mos1S001.arf mos1S001-bkg.arf 
##mv mos1S001-obj-im-sp-det.fits mos2S002-im-sp-det-bkg.fits 
### MOS2
##mv mos2S002-obj.pi  mos2S002-obj-bkg.pi 
##mv mos2S002-back.pi mos2S002-back-bkg.pi 
##mv mos2S002.rmf     mos2S002-bkg.rmf 
##mv mos2S002.arf     mos2S002-bkg.arf 
##mv mos2S002-obj-im-sp-det.fits mos2S002-im-sp-det-bkg.fits 
### PN
##mv pnS003-obj.pi  pnS003-obj-bkg.pi 
##mv pnS003-back.pi pnS003-back-bkg.pi 
##mv pnS003.rmf     pnS003-bkg.rmf 
##mv pnS003.arf     pnS003-bkg.arf 
##mv pnS003-obj-im-sp-det.fits pnS003-sp-bkg.fits 
##mv pnS003-obj-os.pi          pnS003-obj-os-bkg.pi
##
### Group the spectra
##grppha mos1S001-obj-src.pi mos1S001-obj-src-grp.pi 'chkey BACKFILE mos1S001-back-src.pi & chkey RESPFILE mos1S001-src.rmf & chkey ANCRFILE mos1S001-src.arf & group min 50 & exit'
##grppha mos1S001-obj-bkg.pi mos1S001-obj-bkg-grp.pi 'chkey BACKFILE mos1S001-back-bkg.pi & chkey RESPFILE mos1S001-bkg.rmf & chkey ANCRFILE mos1S001-bkg.arf & group min 50 & exit'
##grppha mos2S002-obj-src.pi mos2S002-obj-src-grp.pi 'chkey BACKFILE mos2S002-back-src.pi & chkey RESPFILE mos2S002-src.rmf & chkey ANCRFILE mos2S002-src.arf & group min 50 & exit'
##grppha mos2S002-obj-bkg.pi mos2S002-obj-bkg-grp.pi 'chkey BACKFILE mos2S002-back-bkg.pi & chkey RESPFILE mos2S002-bkg.rmf & chkey ANCRFILE mos2S002-bkg.arf & group min 50 & exit'
##grppha pnS003-obj-src.pi pnS003-obj-src-grp.pi 'chkey BACKFILE pnS003-back-src.pi & chkey RESPFILE pnS003-src.rmf & chkey ANCRFILE pnS003-src.arf & group min 50 & exit'
##grppha pnS003-obj-bkg.pi pnS003-obj-bkg-grp.pi 'chkey BACKFILE pnS003-back-bkg.pi & chkey RESPFILE pnS003-bkg.rmf & chkey ANCRFILE pnS003-bkg.arf & group min 50 & exit'
