#!/bin/bash

if [[ -z "$XMM_PATH" ]]; then
  echo "Source sasinit before running this program"
  exit 1
fi

# Arcsecond symbol \mbox{$^{\prime\prime}$} from aastex6.cls

# 0087940201 MOS1
xs_replotter.py $XMM_PATH/results_spec/20160701_fiveann_spec_01.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_06.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_11.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_16.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_21.dat \
                --components "CXRB" "SP" "Remnant" "Instr. lines" \
                --colors "#4daf4a" "#f781bf" "#e41a1c" "#999999" \
                --labels '0--100\mbox{$^{\prime\prime}$}' \
                         '100--200\mbox{$^{\prime\prime}$}' \
                         '200--300\mbox{$^{\prime\prime}$}' \
                         '300--400\mbox{$^{\prime\prime}$}' \
                         '400--500\mbox{$^{\prime\prime}$}' \
                --ylim '1e-3' '0.5' \
                --residual \
                --out "$XMM_PATH/results_plots/fiveannulus_0087940201_mos1"

# 0087940201 MOS2
xs_replotter.py $XMM_PATH/results_spec/20160701_fiveann_spec_02.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_07.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_12.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_17.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_22.dat \
                --components "CXRB" "SP" "Remnant" "Instr. lines" \
                --colors "#4daf4a" "#f781bf" "#e41a1c" "#999999" \
                --labels '0--100\mbox{$^{\prime\prime}$}' \
                         '100--200\mbox{$^{\prime\prime}$}' \
                         '200--300\mbox{$^{\prime\prime}$}' \
                         '300--400\mbox{$^{\prime\prime}$}' \
                         '400--500\mbox{$^{\prime\prime}$}' \
                --ylim '1e-3' '0.5' \
                --residual \
                --out "$XMM_PATH/results_plots/fiveannulus_0087940201_mos2"

# 0087940201 PN
xs_replotter.py $XMM_PATH/results_spec/20160701_fiveann_spec_03.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_08.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_13.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_18.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_23.dat \
                --components "CXRB" "SP" "Remnant" "Instr. lines" \
                --colors "#4daf4a" "#f781bf" "#e41a1c" "#999999" \
                --labels '0--100\mbox{$^{\prime\prime}$}' \
                         '100--200\mbox{$^{\prime\prime}$}' \
                         '200--300\mbox{$^{\prime\prime}$}' \
                         '300--400\mbox{$^{\prime\prime}$}' \
                         '400--500\mbox{$^{\prime\prime}$}' \
                --ylim '2e-3' '1' \
                --residual \
                --out "$XMM_PATH/results_plots/fiveannulus_0087940201_pn"

# 0551000201 MOS1
xs_replotter.py $XMM_PATH/results_spec/20160701_fiveann_spec_04.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_09.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_14.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_19.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_24.dat \
                --components "CXRB" "SP" "Remnant" "Instr. lines" \
                --colors "#4daf4a" "#f781bf" "#e41a1c" "#999999" \
                --labels '0--100\mbox{$^{\prime\prime}$}' \
                         '100--200\mbox{$^{\prime\prime}$}' \
                         '200--300\mbox{$^{\prime\prime}$}' \
                         '300--400\mbox{$^{\prime\prime}$}' \
                         '400--500\mbox{$^{\prime\prime}$}' \
                --ylim '1e-3' '0.5' \
                --residual \
                --out "$XMM_PATH/results_plots/fiveannulus_0551000201_mos1"

# 0551000201 MOS2
xs_replotter.py $XMM_PATH/results_spec/20160701_fiveann_spec_05.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_10.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_15.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_20.dat \
                $XMM_PATH/results_spec/20160701_fiveann_spec_25.dat \
                --components "CXRB" "SP" "Remnant" "Instr. lines" \
                --colors "#4daf4a" "#f781bf" "#e41a1c" "#999999" \
                --labels '0--100\mbox{$^{\prime\prime}$}' \
                         '100--200\mbox{$^{\prime\prime}$}' \
                         '200--300\mbox{$^{\prime\prime}$}' \
                         '300--400\mbox{$^{\prime\prime}$}' \
                         '400--500\mbox{$^{\prime\prime}$}' \
                --ylim '2e-4' '0.5' \
                --residual \
                --out "$XMM_PATH/results_plots/fiveannulus_0551000201_mos2"
