#!/bin/bash

if [[ -z "$XMM_PATH" ]]; then
  echo "Source sasinit before running this program"
  exit 1
fi

xs_replotter.py $XMM_PATH/results_spec/20160630_src_powerlaw_nonsolar_spec_01.dat \
                --colors "#4daf4a" "#f781bf" "#e41a1c" "#999999" "black" \
                --labels 'Source (0--400\mbox{$^{\prime\prime}$}) with power law' \
                --ylim '1e-3' '2.0' \
                --augment $XMM_PATH/results_spec/20160630_src_powerlaw_nonsolar_powerlaw-only_spec_01.dat \
                --augment-cols 7 \
                --out "$XMM_PATH/results_plots/fig_src_powerlaw_0087940201-mos1"
#                --components "CXRB" "SP" "SNR" "Instr. lines" "Power law"\

xs_replotter.py $XMM_PATH/results_spec/20160630_src_srcutlog_nonsolar_spec_01.dat \
                --colors "#4daf4a" "#f781bf" "#e41a1c" "#999999" "black" \
                --labels 'Source (0--400\mbox{$^{\prime\prime}$}) with srcutlog' \
                --ylim '1e-3' '2.0' \
                --augment $XMM_PATH/results_spec/20160630_src_srcutlog_nonsolar_srcutlog-only_spec_01.dat \
                --augment-cols 7 \
                --out "$XMM_PATH/results_plots/fig_src_srcutlog_0087940201-mos1"
#                --components "CXRB" "SP" "SNR" "Instr. lines" "srcutlog"\
