#!/bin/bash

if [[ -z "$XMM_PATH" ]]; then
  echo "Source sasinit before running this program"
  exit 1
fi

xs_replotter.py $XMM_PATH/results_spec/20160701_src_bkg_spec_01.dat \
                --components "CXRB" "SP" "Remnant" "Instr. lines" \
                --colors "#4daf4a" "#f781bf" "#e41a1c" "#999999" \
                --labels 'Source (0--400\mbox{$^{\prime\prime}$})' \
                --ylim '1e-3' '2.0' \
                --no-x-labels \
                --out "$XMM_PATH/results_plots/fig_src_bkg_0087940201-mos1_top"

xs_replotter.py $XMM_PATH/results_spec/20160701_src_bkg_spec_06.dat \
                --colors "#4daf4a" "#f781bf" "#999999" \
                --labels 'Background (510--700\mbox{$^{\prime\prime}$})' \
                --ylim '1e-3' '1.0' \
                --out "$XMM_PATH/results_plots/fig_src_bkg_0087940201-mos1_bottom"
# Omit --components to remove legend
# --components "CXRB" "SP" "Instr. lines" \
