#!/bin/bash

if [[ -z "$XMM_PATH" ]]; then
  echo "Source sasinit before running this program"
  exit 1
fi

nums=("01" "02" "03" "04" "05")
names=("0087940201-mos1" "0087940201-mos2" "0087940201-pn" \
       "0551000201-mos1" "0551000201-mos2")
# Configured for center region annulus
ymins=("1e-3" "1e-3" "2e-3" "1e-3" "1e-4")
ymaxs=("0.2" "0.2" "0.5" "0.3" "0.3")

# MANUAL OVERRIDE TO PLOT ONLY ONE
#nums=("03")
#names=("0087940201-pn")
## Configured for center region annulus
#ymins=("2e-3")
#ymaxs=("0.5")


for ((i=0;i<${#nums[@]};++i)); do

  num="${nums[$i]}"
  name="${names[$i]}"  # obsid-exp
  ymin="${ymins[$i]}"
  ymax="${ymaxs[$i]}"

  xs_replotter.py "$XMM_PATH/results_spec/20160706_fourann_stock_spec_${num}.dat" \
                  "$XMM_PATH/results_spec/20160708_fourann_center-mg-free_spec_${num}.dat" \
                  "$XMM_PATH/results_spec/20160708_fourann_center-mg-o-free_spec_${num}.dat" \
                  "$XMM_PATH/results_spec/20160708_fourann_center-mg-ne-free_spec_${num}.dat" \
                  "$XMM_PATH/results_spec/20160708_fourann_center-mg-fe-free_spec_${num}.dat" \
                  "$XMM_PATH/results_spec/20160708_fourann_center-mg-o-ne-free_spec_${num}.dat" \
                  "$XMM_PATH/results_spec/20160712_fourann_center-mg-o-fe-free_spec_${num}.dat" \
                  --augment "$XMM_PATH/results_spec/20160708_fourann_center-mg-free_spec_${num}.dat" \
                            "$XMM_PATH/results_spec/20160708_fourann_center-mg-free_spec_${num}.dat" \
                            "$XMM_PATH/results_spec/20160708_fourann_center-mg-free_spec_${num}.dat" \
                            "$XMM_PATH/results_spec/20160708_fourann_center-mg-free_spec_${num}.dat" \
                            "$XMM_PATH/results_spec/20160708_fourann_center-mg-free_spec_${num}.dat" \
                            "$XMM_PATH/results_spec/20160708_fourann_center-mg-free_spec_${num}.dat" \
                            "$XMM_PATH/results_spec/20160708_fourann_center-mg-free_spec_${num}.dat" \
                  --augment-cols 7 \
                  --components "CXRB" "SP" "SNR" "Instr. lines" "Si,S,Mg" \
                  --colors "#4daf4a" "#f781bf" "#e41a1c" "#999999" "#000000" \
                  --linestyles "solid" "solid" "solid" "solid" "dotted" \
                  --labels '0--100\mbox{$^{\prime\prime}$}: Si,S' \
                           '0--100\mbox{$^{\prime\prime}$}: Si,S,Mg' \
                           '0--100\mbox{$^{\prime\prime}$}: Si,S,Mg,O' \
                           '0--100\mbox{$^{\prime\prime}$}: Si,S,Mg,Ne' \
                           '0--100\mbox{$^{\prime\prime}$}: Si,S,Mg,Fe' \
                           '0--100\mbox{$^{\prime\prime}$}: Si,S,Mg,O,Ne' \
                           '0--100\mbox{$^{\prime\prime}$}: Si,S,Mg,O,Fe' \
                  --ylim "$ymin" "$ymax" \
                  --residual \
                  --out "$XMM_PATH/results_plots/fig_fourann-varycenter_${name}"

done
