#!/bin/tcsh
#
# Wrapper script to prepare XMM-Newton ODF files for processing
# (cifbuild, odfingest)
#
# Required directory structure
#     ./$obsid
#     ./$obsid/odf
#     ./$obsid/pps  # Not sure if this is actually needed
#   and the script will create output products in
#     ./$obsid/odf/repro
#
# Basically, you must run this from the top-level directory
# /data/mpofls/atran/research/g309/xmm/
#
# AND, you must have run $XMM_PATH/sasinit first, to set environment variables.
#
# atran@treble$ source sasinit
# atran@treble$ source sasrepro
#
# In principle, "source" should not be needed for sasrepro invocation.
# But, required because $path env variable is not propagated to tcsh subshells
# this appears to be an issue only on CfA/HEAD machines.
# Could be fixed by using "#! /bin/tcsh -f" here?
#
# A. Tran, 2015 Nov 13

set obsid = $argv[1]

# Set up directory structure
setenv SAS_ODF $XMM_PATH/$obsid/odf  # For cifbuild run before odfingest
set repro = $XMM_PATH/$obsid/odf/repro
mkdir -p $repro
cd $repro

cifbuild  # outputs ccf.cif in current directory
setenv SAS_CCF $XMM_PATH/$obsid/odf/repro/ccf.cif

odfingest  # outputs $(REV)_$(OBSID)_SCX00000SUM.SAS in current directory
setenv SAS_ODF $XMM_PATH/`ls -1 *SUM.SAS`

