#!/bin/tcsh -f
#
# Prepare XMM-Newton ODF files for processing (cifbuild, odfingest)
# Creates directory structure:
#
#     $XMM_PATH/$obsid
#     $XMM_PATH/$obsid/odf
#     $XMM_PATH/$obsid/pps
#     $XMM_PATH/$obsid/odf/repro
#
# Requires SAS environment with XMM_PATH env variable set
#
# A. Tran, 2015 Nov 13

set obsid = $argv[1]

if (! $?XMM_PATH) then
  echo "ERROR: XMM_PATH not set; source sasinit"
  exit 1
endif

# Set up directory structure
setenv SAS_ODF $XMM_PATH/$obsid/odf  # For cifbuild run before odfingest
set repro = $XMM_PATH/$obsid/odf/repro
mkdir -p $repro
cd $repro

cifbuild >& cifbuild.log # outputs ccf.cif in current directory
setenv SAS_CCF $XMM_PATH/$obsid/odf/repro/ccf.cif

odfingest >& odfingest.log # outputs $(REV)_$(OBSID)_SCX00000SUM.SAS in current directory
setenv SAS_ODF $XMM_PATH/`ls -1 *SUM.SAS`

