#!/bin/bash

# Procedure for straight background subtraction:
# create (src - qpb_src) with BACKFILE = (back - qpb_back)

OBSIDS="0087940201 0551000201"

for obsid in $OBSIDS;
do

  cd "${XMM_PATH}/${obsid}/odf/repro"

  # Slew of file copying; mathpha will not accept dashes in filenames
  fstems="mos1S001_src mos2S002_src mos1S001_bkg mos2S002_bkg"
  cp mos1S001-src.pi     mos1S001_src.pi
  cp mos1S001-src-qpb.pi mos1S001_src_qpb.pi
  cp mos1S001-bkg.pi     mos1S001_bkg.pi
  cp mos1S001-bkg-qpb.pi mos1S001_bkg_qpb.pi
  cp mos2S002-src.pi     mos2S002_src.pi
  cp mos2S002-src-qpb.pi mos2S002_src_qpb.pi
  cp mos2S002-bkg.pi     mos2S002_bkg.pi
  cp mos2S002-bkg-qpb.pi mos2S002_bkg_qpb.pi
  if [[ $obsid = "0087940201" ]]; then
    fstems="${fstems} pnS003_src_os pnS003_bkg_os"
    cp pnS003-src-os.pi  pnS003_src_os.pi
    cp pnS003-src-qpb.pi pnS003_src_os_qpb.pi
    cp pnS003-bkg-os.pi  pnS003_bkg_os.pi
    cp pnS003-bkg-qpb.pi pnS003_bkg_os_qpb.pi
  fi

  # Subtract QPB spectra
  for fstem in $fstems;
  do
    # Spectrum units: (c)ounts, (r)ate
    uflag='C'
    if [[ $fstem =~ "pn" ]]; then
      uflag='R'
    fi
    mathpha expr="${fstem}.pi - ${fstem}_qpb.pi" outfil="!${fstem}_sqpb.pi" \
        units="${uflag}" properr='yes' \
        exposure="${fstem}.pi" backscal='%' areascal='%' \
        ncomments=0
    # areascal=1; backscal is same for QPB and observation spectra
    # Exposure + auxfiles set by src/bkg spectrum; QPB subtraction does not
    # change exposure, area scaling, etc.
    # auxfiles sets: backfile, backscal, corrfile, corrscal, respfile, ancrfile

    # raw spectrum has cts w/ Poisson error (keyword POISSERR='T')
    # QPB has cts and statistical error, much smaller than Poisson error
    # subtracting spectra -> Gaussian errors > POISS-0 errors
    # and anyways, any of POISS-0,1,2,3 will fail on channels with negative
    # counts (which does occur)

    # From mathpha manpage:
    # > If spectra are being subtracted then there is no general 
    # > solution because the difference of two Poisson distributions is not 
    # > itself Poisson (unlike the Gaussian case).

    # We will bin the data before fitting, anyways.
  done

  # Remove temporary files
  rm mos1S001_src.pi
  rm mos1S001_src_qpb.pi
  rm mos1S001_bkg.pi
  rm mos1S001_bkg_qpb.pi
  rm mos2S002_src.pi
  rm mos2S002_src_qpb.pi
  rm mos2S002_bkg.pi
  rm mos2S002_bkg_qpb.pi
  if [[ $obsid = "0087940201" ]]; then
    rm pnS003_src_os.pi
    rm pnS003_src_os_qpb.pi
    rm pnS003_bkg_os.pi
    rm pnS003_bkg_os_qpb.pi
  fi

  # TODO add ARF scaling correction for 0-5keV range.
  # create alternative "arfcorr" files
  # pending further discussion.

  # Set keywords and group.  Note that group simply sets group column in
  # spectrum; information is not lost.  Excess counts at highest channels (but
  # < min bin size) are flagged as BAD and discarded.
  grppha infile="mos1S001_src_sqpb.pi" outfile="!mos1S001_src_sqpb.pi" \
    comm="chkey BACKFILE mos1S001_bkg_sqpb.pi & \
          chkey RESPFILE mos1S001-src.rmf & \
          chkey ANCRFILE mos1S001-src.arf & \
          group min 50 & exit" \
    chatter=10
  grppha infile="mos2S002_src_sqpb.pi" outfile="!mos2S002_src_sqpb.pi" \
    comm="chkey BACKFILE mos2S002_bkg_sqpb.pi & \
          chkey RESPFILE mos2S002-src.rmf & \
          chkey ANCRFILE mos2S002-src.arf & \
          group min 50 & exit" \
    chatter=10

  if [[ $obsid = "0087940201" ]]; then
    grppha infile="pnS003_src_os_sqpb.pi" outfile="!pnS003_src_os_sqpb.pi" \
      comm="chkey BACKFILE pnS003_bkg_os_sqpb.pi & \
            chkey RESPFILE pnS003-src.rmf & \
            chkey ANCRFILE pnS003-src.arf & \
            group min 50 & exit" \
      chatter=10
  fi

done
