#!/bin/bash

# Set up CALDB
mkdir -p caldb
curl "ftp://xmm.esac.esa.int/pub/ccf/constituents/extras/esas_caldb/esas-caldb-sasv13.tar.gz" \
    -o esas-caldb-sasv13.tar.gz --verbose --user anonymous:-curl@
tar -xzvf esas-caldb-sasv13.tar.gz --directory caldb
gunzip caldb/*.rsp.gz


