#!/bin/bash

# Create full FOV images in multiple energy bands.
# WARNING: this task is strongly coupled to the scripts:
#   mos-spectra-mod-skip-rmfarfgen
#   pn-spectra-mod-skip-rmfarfgen
# and they should be viewed as a single unit of code.

# For reference, the ESAS soft proton energy bands are:
# 300-750, 750-1250, 1250-2000, 2000-4000, 4000-8000, 8000-12000 (eV)

# One broad band, three narrow line bands (Mg, Si, S), four continuum bands
# No leading zeros; must write out in integer format in order to correctly
# construct ESAS filenames
#   OK: 800, 3300, 12500
#   NOT OK: 0800, 1e5, 12e4, ...
#PI_MINS=( "800" "1300" "1800" "2400" "1150" "1600" "1980" "2600")
#PI_MAXS=("3300" "1400" "1900" "2500" "1250" "1650" "2050" "2700")
#MASK_FINAL_OUTPUT_FLAGS=("1" "1" "1" "1" "1" "1" "1" "1")

# create images with NO masks for point source display
# 800-3300 to cover broad band, also 1000-2000 for images at top of ARF
# (reduce possible systematics from ARF energy dependence)
PI_MINS=( "800" "1000")
PI_MAXS=("3300" "2000")
MASK_FINAL_OUTPUT_FLAGS=("0" "0")

# Bands manually chosen by inspecting integrated source spectra:
# $ xs_replotter.py replot_src_bkg.yaml
#
# Si 1.8-1.9 is a narrow cut that misses a lot of Si flux.
# Same for S 2.4-2.5, Mg 1.3-1.4.  But, this avoids instrumental lines
# and should yield reasonable signal/noise.
#
# 0087940201 PN could benefit from broader line cuts.
# 0551000201 MOS could tweak Si to avoid bright instrumental line.
# Do make images with MOS only, then add PN.

CALDB="${XMM_PATH}/caldb"

if [[ "$SAS_OBSID" == "0087940201" ]]; then

  exps=("mos1S001" "mos2S002" "pnS003")
  exps_n=("1S001" "2S002" "S003")
  ccd_strs=("ccd1=1 ccd2=1 ccd3=1 ccd4=1 ccd5=1 ccd6=1 ccd7=1" \
            "ccd1=1 ccd2=1 ccd3=1 ccd4=1 ccd5=1 ccd6=1 ccd7=1" \
            "quad1=1 quad2=1 quad3=1 quad4=1")
  # s/quad/ccd/ for ESAS task proton
  proton_ccd_strs=("ccd1=1 ccd2=1 ccd3=1 ccd4=1 ccd5=1 ccd6=1 ccd7=1" \
                   "ccd1=1 ccd2=1 ccd3=1 ccd4=1 ccd5=1 ccd6=1 ccd7=1" \
                   "ccd1=1 ccd2=1 ccd3=1 ccd4=1")
  # Assumes power law; bkg_pnorms, pindices taken from 20161015_src_bkg_mg.log
  bkg_pnorms=("0.0587213" "0.0587213" "0.0663454")
  pindices=("0.355124" "0.355124" "0.253715")
  # pnorm = sp_partial_factor * bkg_pnorm
  pnorms=("0.2567173" "0.2552315" "0.2936542")

elif [[ "$SAS_OBSID" == "0551000201" ]]; then

  # Skip pnS003, large window mode has no corner data to use
  exps=("mos1S001" "mos2S002")
  exps_n=("1S001" "2S002")
  # 0551000201 MOS1 CCD6 = 0 (destroyed), MOS2 CCD5 = 0 (anomalous state)
  ccd_strs=("ccd1=1 ccd2=1 ccd3=1 ccd4=1 ccd5=1 ccd6=0 ccd7=1" \
            "ccd1=1 ccd2=1 ccd3=1 ccd4=1 ccd5=0 ccd6=1 ccd7=1")
  # No PN exposures, so use same $ccd_strs for ESAS task proton
  proton_ccd_strs=$ccd_strs
  # Assumes power law; bkg_pnorms, pindices taken from 20161015_src_bkg_mg.log
  bkg_pnorms=("0.0243880" "0.0243880")
  pindices=("0.488202" "0.488202")
  # pnorm = sp_partial_factor * bkg_pnorm
  pnorms=("0.079018742" "0.077613033")

else

  echo "ERROR: unsupported obsid $SAS_OBSID (pipeline not set up)"
  exit 1

fi

# Ensure that we always create full FOV spectrum + RMF on first
# energy band run.
for ((j=0;j<${#exps[@]};++j)); do
  echo "Check that non-clobbered files will be created on first mos/pn-spectra run"
  exp="${exps[$j]}"

  cd $SAS_REPRO

  if [[ -e "${exp}-obj.pi" ]]; then
    echo "Spectrum ${exp}-obj.pi exists, please remove and try again"
    exit 255
  fi
  if [[ -e "${exp}.rmf" ]]; then
    echo "RMF ${exp}.rmf exists, please remove and try again"
    exit 255
  fi
  if [[ "$exp" =~ "pn" && -e "${exp}-obj-oot.pi" ]]; then
    echo "Spectrum ${exp}-obj-oot.pi exists, please remove and try again"
    exit 255
  fi
done

for ((i=0;i<${#PI_MINS[@]};++i)); do

  elow="${PI_MINS[$i]}"
  ehigh="${PI_MAXS[$i]}"
  mask_final_output="${MASK_FINAL_OUTPUT_FLAGS[$i]}"

  echo "Extracting $SAS_OBSID images in ${elow}-${ehigh} eV range"
  echo "  mask_final_output=${mask_final_output}"
  start_script="Start: $(date)"
  echo $start_script

  cd $SAS_REPRO

  for ((j=0;j<${#exps[@]};++j)); do

    # Setup
    # -----
    exp="${exps[$j]}"     # mos1S001
    exp_n="${exps_n[$j]}" # 1S001
    ccd_str="${ccd_strs[$j]}" # "ccd1=1 ccd2=1 ... ccd7=1"
    proton_ccd_str="${proton_ccd_strs[$j]}"
    bkg_pnorm="${bkg_pnorms[$j]}"
    pindex="${pindices[$j]}"
    pnorm="${pnorms[$j]}"
    # Do not quote ${ccd_str} in command invocations!

    echo "  Operating on $exp ($exp_n); indices i = $i, j = $j"
    echo "    CCD selection: $ccd_str"
    echo "    Proton CCD selection: $proton_ccd_str"
    echo "    Proton parameters: bkg_pnorm=$bkg_pnorm, index=$pindex, pnorm=$pnorm"

    if [[ $exp =~ "mos" ]]; then
      exe_spec="mos-spectra-mod-skip-rmfarfgen"
      exe_qpb="mos_back"
    elif [[ $exp =~ "pn" ]]; then
      exe_spec="pn-spectra-mod-skip-rmfarfgen"
      exe_qpb="pn_back"
    else
      echo "ERROR: Got bad exposure string $exp"
      exit 1
    fi

    # list of files that must be swapped in/out if you want to change
    # masking for image mosaics
    # ~~~~~~~~~~~~~~~~~~~~
    # WARNING: FILE LIST EDITS MUST BE PROPAGATED TO
    #   prepare_images_for_mosaicking.sh
    # 1. I don't think "im-det" files are needed, but symlink to be sure
    # 2. ${exp}-back-im-det/sky-* files omitted because I want to use unmasked
    #    images (mask-0) in all cases; this is assured by specbackprot_image.
    # ~~~~~~~~~~~~~~~~~~~~
    BASENAMES="${exp}-obj-im-det-${elow}-${ehigh}
               ${exp}-obj-im-${elow}-${ehigh}
               ${exp}-exp-im-${elow}-${ehigh}
               ${exp}-mask-im-${elow}-${ehigh}
              "
    if [[ $exp =~ "pn" ]]; then
      BASENAMES="${BASENAMES}
                 ${exp}-obj-im-det-${elow}-${ehigh}-oot
                 ${exp}-obj-im-${elow}-${ehigh}-oot
                 ${exp}-exp-im-det-${elow}-${ehigh}
                 ${exp}-mask-im-det-${elow}-${ehigh}
                "
    fi

    # Extraction
    # ----------

    # FIRST RUN, ${exe_spec} MASK=0
    # (create non-masked background images.  This requires many non-masked
    # intermediate files, so must run ${exe_spec} twice; we cannot just extract
    # relevant evselect calls)

    echo "  Running ${exe_spec} prefix=${exp_n} elow=${elow} ehigh=${ehigh} mask=0..."
    ${exe_spec} prefix=${exp_n} region="" caldb="${CALDB}" \
        mask=0 elow=${elow} ehigh=${ehigh} ${ccd_str} \
      &> "${exe_spec}_${exp}_FOV_${elow}_${ehigh}_mask-0.log"
    mv command.csh "${exe_spec}_${exp}_FOV_${elow}_${ehigh}_mask-0_cmd.csh"

    echo "  Running ${exe_qpb} mask=0..."
    ${exe_qpb} prefix=${exp_n} caldb="${CALDB}" diag=2 clobber=1 \
        elow=${elow} ehigh=${ehigh} ${ccd_str} \
      &> "${exe_qpb}_${exp}_FOV_${elow}_${ehigh}_mask-0.log"
    # diag=2 creates more diagnostic output files (.qdp plots)

    # Rotate background image
    rot-im-det-sky prefix=${exp_n} elow=${elow} ehigh=${ehigh} mode=1 \
      &> "rot-im-det-sky_${exp}_FOV_${elow}_${ehigh}_mode-1_mask-0.log"

    # Migrate outputs to "mask-0"
    for base in $BASENAMES; do
      mv "${base}.fits" "${base}_mask-0.fits"  
    done
    mv "${exp}-back-im-det-${elow}-${ehigh}.fits" "${exp}-back-im-det-${elow}-${ehigh}_mask-0.fits"
    mv "${exp}-back-im-sky-${elow}-${ehigh}.fits" "${exp}-back-im-sky-${elow}-${ehigh}_mask-0.fits"


    # SECOND RUN, ${exe_spec} MASK=1
    # (clobber everything and create masked images, spectra)
    if [[ $mask_final_output == "1" ]]; then
      echo "  Running ${exe_spec} prefix=${exp_n} elow=${elow} ehigh=${ehigh} mask=1..."
      ${exe_spec} prefix=${exp_n} region="" caldb="${CALDB}" \
          mask=1 elow=${elow} ehigh=${ehigh} ${ccd_str} \
        &> "${exe_spec}_${exp}_FOV_${elow}_${ehigh}_mask-1.log"
      mv command.csh "${exe_spec}_${exp}_FOV_${elow}_${ehigh}_mask-1_cmd.csh"

      echo "  Running ${exe_qpb} mask=1..."
      ${exe_qpb} prefix=${exp_n} caldb="${CALDB}" diag=2 clobber=1 \
          elow=${elow} ehigh=${ehigh} ${ccd_str} \
        &> "${exe_qpb}_${exp}_FOV_${elow}_${ehigh}_mask-1.log"
      # diag=2 creates more diagnostic output files (.qdp plots)

      # Rotate background image
      rot-im-det-sky prefix=${exp_n} elow=${elow} ehigh=${ehigh} mode=1 \
        &> "rot-im-det-sky_${exp}_FOV_${elow}_${ehigh}_mode-1_mask-1.log"

      # Migrate outputs to "mask-1"
      for base in $BASENAMES; do
        mv "${base}.fits" "${base}_mask-1.fits"  
      done
      mv "${exp}-back-im-det-${elow}-${ehigh}.fits" "${exp}-back-im-det-${elow}-${ehigh}_mask-1.fits"
      mv "${exp}-back-im-sky-${elow}-${ehigh}.fits" "${exp}-back-im-sky-${elow}-${ehigh}_mask-1.fits"

    else
      echo "  Skipping mask=1 runs of ${exe_spec}, ${exe_qpb}"
    fi

    echo "Use unmasked QPB image even if mask=1"
    echo "(consistent with ESAS 'proton' image and allows source hole filling)"
    ln -s -v "${exp}-back-im-det-${elow}-${ehigh}_mask-0.fits" "${exp}-back-im-det-${elow}-${ehigh}.fits" 
    ln -s -v "${exp}-back-im-sky-${elow}-${ehigh}_mask-0.fits" "${exp}-back-im-sky-${elow}-${ehigh}.fits"

    # Point ESAS files to masked or unmasked products
    select_images_for_mosaicking.sh ${elow} ${ehigh} ${mask_final_output}

    # Soft proton
    # -----------
    # Bootstrapping issue: sp_partial must be run BEFORE proton
    # Requires -bkg.pi spectrum to have been extracted.
    # kind of a pain, but OK.

    # proton and swcx tasks only operate on files named "elow", "ehigh"
    # and so can be run after the above renaming.

    if [[ $exp =~ "mos1" ]]; then
      detector_n=1
    elif [[ $exp =~ "mos2" ]]; then
      detector_n=1
    elif [[ $exp =~ "pn" ]]; then
      detector_n=3
    fi

    # Q: is it necessary to use OOT-subtracted spectrum for PN in sp_partial
    # and proton calls?
    # A: no, backscal/exposure are the same between OOT-subtracted and
    # non-OOT-subtracted spectra.

    echo "  Running sp_partial prefix=${exp_n} with rnorm=${bkg_pnorm}..."
    sp_partial caldb=${CALDB} detector=${detector_n} \
        fullimage="${exp}-obj-im-sp-det.fits" fullspec="${exp}-obj.pi" \
        regionimage="${exp}-bkg-im-sp.fits" regionspec="${exp}-bkg.pi" \
        rnorm=${bkg_pnorm} \
      &> "sp_partial_${exp}_FOV_${elow}_${ehigh}_mask-${mask_final_output}.log"

    echo "  Running proton prefix=${exp_n}..."
    # proton uses mask-dependent files to get exposure time and FITS header,
    # but SP image is unaffected by presence or absence of mask on inputs;
    # output only depends on scalar parameters
    # (elow, ehigh, ccds, pindex, pnorm, ...)
    proton prefix=${exp_n} caldb="${CALDB}" specname="${exp}-obj.pi" \
        elow=${elow} ehigh=${ehigh} ${proton_ccd_str} \
        pindex=${pindex} pnorm=${pnorm} spectrumcontrol=1 \
      &> "proton_${exp}_FOV_${elow}_${ehigh}.log"
    # Rotate proton image
    rot-im-det-sky prefix=${exp_n} elow=${elow} ehigh=${ehigh} mode=2 \
      &> "rot-im-det-sky_${exp}_FOV_${elow}_${ehigh}_mode-2.log"

  done

  echo "Finished extracting $SAS_OBSID images in ${elow}-${ehigh} eV range"
  echo $start_script
  echo "Finished: $(date)"
done

# After all files created, move FOV spectrum files that do NOT depend
# upon energy band.  This allows seamless re-run of specbackprot_image.
#
# ESAS by default won't clobber existing ${exp}-obj.pi,  ${exp}.rmf,
# which introduces big risk of using wrong file from previous subregion
# extraction.  So, specbackprot_image checks to ensure these files don't exist
# at the top.  The renamed FOV files aren't used in subsequent processing, but
# are kept for convenience (e.g., you could move the FOV files back before
# re-running specbackprot_image).
for ((j=0;j<${#exps[@]};++j)); do

  exp="${exps[$j]}"

  echo "Rename output files (map ${exp} to ${exp}-FOV)"
  # Keep file names consistent with "specbackgrp" as much as possible

  mv "${exp}-obj.pi"      "${exp}-FOV.pi"
  mv "${exp}-back.pi"     "${exp}-FOV-qpb.pi"
  mv "${exp}.rmf"         "${exp}-FOV.rmf"
#  mv "${exp}.arf"         "${exp}-FOV.arf"  # No ARF files created
  mv "${exp}-obj-im-sp-det.fits" "${exp}-FOV-im-sp.fits"
  if [[ "$exp" =~ "pn" ]]; then
    mv "${exp}-obj-oot.pi"    "${exp}-FOV-oot.pi"
    mv "${exp}-obj-os.pi"     "${exp}-FOV-os.pi"
  fi

done

